### ISSUE TITLE
Progress Bar Flickers on Safari 

### ISSUE THREAD

**Issue by ozgurduygu** [google/model-viewer#1024]
I think this issue is related to a webkit issue where css3 transitions trigger a flicker on the affected elements. I could solve the issue by applying `-webkit-transform:translateZ(0);` to elements related and keeping the transition time above `0.3s`. Default value of `0.09s` could not reliably solve the issue. 

```css
#default-progress-bar > .bar {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: var(--progress-bar-height, 5px);
  transform-origin: top left;
  transition: transform 0.3s;
  transform: scaleY(0);
  overflow: hidden;
  -webkit-transform:translateZ(0);
}
```

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows
