### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by muuvmuuv** [google/model-viewer#4091]
### Description

In Angular with the latest 3.x release, I am getting this warning from Webpack.

```
./node_modules/.pnpm/@google+model-viewer@3.0.0/node_modules/@google/model-viewer/lib/three-components/TextureUtils.js:62:18-47 - Warning: Critical dependency: the request of a dependency is an expression
```

#### Live Demo

https://glitch.com/edit/#!/model-viewer

I don't think one is needed, it's just the way the dep is imported.
https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

### Version

- model-viewer: v3.X.X

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
I would guess this is related to #4090? The basic issue is that the library to load lottie animations is as large as model-viewer itself, so we definitely don't want to pack it into our bundle. I designed it to lazy-load as needed just like the DRACO decoder. However, it sounds like something I did is confusing some of the tooling systems - help would be much appreciated. Does anyone know why it complains for Lottie but not for DRACO?

**Comment by muuvmuuv** [comment]
Maybe I can setup a repl with webpack but I guess it will alteady be resolved if added as optional/peerDependency. And yes its related so we can close this one if you want?

**Comment by elalish** [comment]
Okay, sounds good.

**Comment by muuvmuuv** [comment]
So, #4090 is fixed, but now I need to explicitly install three otherwise the build fails and even if installed I still get this Webpack warning… :(

**Comment by marcogianni** [comment]
I also have the same warning with three already installed.
`
./node_modules/@google/model-viewer/lib/three-components/TextureUtils.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@google/model-viewer/lib/three-components/TextureUtils.js
./node_modules/@google/model-viewer/lib/three-components/Renderer.js
./node_modules/@google/model-viewer/lib/features/loading.js
./node_modules/@google/model-viewer/lib/model-viewer.js
./components/3d-assets/SingleAssetImage.js
`

**Comment by muuvmuuv** [comment]
Got it reproduced here: https://codesandbox.io/p/sandbox/plain-webpack-outu3n?selection=%5B%7B%22endColumn%22%3A27%2C%22endLineNumber%22%3A23%2C%22startColumn%22%3A27%2C%22startLineNumber%22%3A23%7D%5D&file=%2Fwebpack.config.js

**Comment by muuvmuuv** [comment]
Also found this https://webpack.js.org/api/module-methods/

<img width="715" alt="Bildschirm­foto 2023-02-27 um 08 55 29" src="https://user-images.githubusercontent.com/11534760/221505792-a203f594-0674-44f8-a599-96f4bc396a7f.png">

I have confirmed that this would remove the warning but idk if this breaks other functionallity. Further reading: https://github.com/webpack/webpack/issues/7713#issuecomment-467888437

**Comment by muuvmuuv** [comment]
Seems to be the right thing after reading this one here: https://github.com/webpack/webpack/issues/15957

Webpack will always try to import it/or node.

**Comment by muuvmuuv** [comment]
@elalish just found that NX is doing it the same way :) so guess its fine model-viewer adapts it: https://github.com/nrwl/nx/blob/master/packages/angular/mf/mf.ts#L41

**Comment by syui** [comment]
I get an error in vue.
By the way, the build succeeds on local (mac-m1).

```yml
name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        ref: main
        submodules: true
        fetch-depth: 0
    - run: |
           yarn install
           yarn add @google/model-viewer

    - name: Build
      env: 
        TZ: "Asia/Tokyo"
      run: |
           yarn build
```

> src/App.vue

```js
computed: {
			loadComponent() {
				return () => import('@google/model-viewer');
			}
		},
```

```json
"node_modules/@google/model-viewer": {
      "version": "3.2.1",
      "license": "Apache-2.0",
      "dependencies": {
        "lit": "^2.7.2"
      },
      "engines": {
        "node": ">=6.0.0"
      },
      "peerDependencies": {
        "three": "^0.154.0"
      }
    },
```
