### ISSUE TITLE
Fade in 3D model when ready

### ISSUE THREAD

**Issue by jmbattle0** [google/model-viewer#5044]
Hello, 

I am working on a digital piano model viewer tool for my company's website.
I would like to ask if it's possible to configure modelviewer to fade in the model one it has loaded, rather than simply appearing.

Currently I am setting the opacity of the modelviewer div to 0, then increasing the opacity when the model has loaded. This method works, however, it means the poster image, progress bar etc. elements are (for the most part) not visible.
Here is a demo: https://www.kawai-global.com/3dtest/?model=CA901

It would be preferable if there was a method to fade-in *just* the model, rather than the entire modelviewer area.

Many thanks!

**Comment by smirnov-artur** [comment]
You can get this today without fading the host element — but the fade has to live on an element you own, because nothing inside `<model-viewer>` cross-fades on its own.

Two things from the source that explain why your current approach takes the poster and progress bar down with it:

1. The poster container is switched with `display`, not `opacity`:

```css
.slot.poster      { display: none; background-color: inherit; }
.slot.poster.show { display: inherit; }
```

(`packages/model-viewer/src/template.ts`). `[$hidePoster]()` just does `posterContainerElement.classList.remove('show')` — a hard cut, nothing to transition.

2. The canvas is not exposed as a CSS part. The only `part=` names in the template are `default-ar-button`, `default-progress-bar` and `default-exit-webxr-ar-button`, so there is no supported hook to touch the canvas from outside. Fading the host is the only thing left — which is exactly why your poster and progress bar go with it.

## What works

Put your own poster in the `poster` slot, fade **that** out, and dismiss it when the fade ends. The host stays at `opacity: 1` the whole time, so the progress bar keeps rendering.

```html
<model-viewer id="mv" src="CA901.glb" loading="eager" reveal="manual">
  <div slot="poster" id="poster"></div>
</model-viewer>
```

```css
#poster {
  width: 100%; height: 100%;
  background: #fff url(CA901-poster.jpg) center / contain no-repeat;
  opacity: 1;
  transition: opacity .4s ease;
}
#poster.fade { opacity: 0; }

/* still visible, because the host is never faded */
#mv::part(default-progress-bar) { background-color: #c00; }
```

```js
const mv = document.getElementById('mv');
const poster = document.getElementById('poster');

mv.addEventListener('load', () => {
  poster.addEventListener('transitionend', () => mv.dismissPoster(), { once: true });
  poster.classList.add('fade');
});
```

The model is already loaded and rendering under the poster while it fades, so what the user sees is the model coming up rather than a swap.

## One trap worth naming

`loading="eager"` is load-bearing here, not decoration. From the `loading` docs in `features/loading.ts`:

> Auto is equivalent to lazy, which loads the model when it is near the viewport for reveal = "auto", **and when `dismissPoster()` is called for reveal = "manual"**.

So with `reveal="manual"` and the default `loading`, the model does not begin loading until you call `dismissPoster()` — meaning `load` never fires, your handler never runs, and the poster sits there forever. `loading="eager"` breaks that deadlock.

If you need a hook for the moment the swap actually happened, `[$hidePoster]()` dispatches `poster-dismissed` at the end.

## A dead end, so you don't spend a day on it

The template also contains

```html
<div class="slot canvas">
  <slot name="canvas"><canvas></canvas></slot>
</div>
```

which reads like an invitation to supply your own canvas in light DOM and style it. It is not one. `model-viewer-base.ts` picks the canvas up with

```js
this[$canvas] = shadowRoot.querySelector('canvas') as HTMLCanvasElement;
```

so a light-DOM `<canvas slot="canvas">` is never adopted — you would be styling an element nothing renders into.

As a feature request, the thing that would remove the need for all of the above is exposing the canvas as a part (`part="canvas"`), or a `reveal-transition`/`fade-duration` attribute that applies the transition to the canvas instead of the host.
